WIN_WIDTH =640
WIN_HEIGHT=480
PLAYER_LAYER=3
BLUE=(0,0,255)
GROUND_LAYER=1
BLOCK_LAYER=2
TILESIZE=32
RED=(255,0,0)
BLACK=(0,0,0)
WHITE=(255,255,255)
FPS=60
PLAYER_SPEED=3
tilemap=[
    'B..C..BBBBBBBBBBBBB',
    'B.............T...B',
    'B.................B',
    'B.................B',
    'B.................B',
    'B.........P.......B',
    'B.................B',
    'B.................B',
    'B.................B',
    'B.................B',
    'B....T.......T....B',
    'B.................B',
    'B.................B',
    'B.................B',
    'BBBBBBBBBBBBBBBBBBB',

]